fieldLayouts:
  c05a3972-dbae-4c1e-a31a-a8290f872916:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Testimonial
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 67a4503f-3a3b-4cf2-8e69-826b73d09cee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 65f776b0-13c1-4b50-8149-1703476b076b # Testimonial Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21d65745-8956-454d-b462-8cfacee00654
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9e0a1e1-0957-49a3-9b43-c2212513f04d # Testimonial Byline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 099ddb47-9e88-4e61-93b0-caf0b0b26d62
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df838e70-1a98-4b5c-8de1-5681a4596535
        userCondition: null
handle: default
hasTitleField: false
name: Default
section: 4ecec9de-d3f7-4f19-ad73-94e4db9fb59f # Testimonials
sortOrder: 1
titleFormat: '{testimonialByline[0].fullName}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
